name = "derevnja aoc"
author = "kotkislot"
version = "2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d372eca41ff1319b39e210a90052f8bca03ca440966055848036c865c3b01d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
