name = "derevnja aoc"
author = "kotkislot"
version = "2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7880091327dab4dc30ece8a1741cbc17fd40320e4922f2efb000b79a7f05085d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
